export const PAGE_TYPE = { offset: 0, size: 1 }
export const FREE_BLOCK = { offset: 1, size: 2 }
export const NUMBER_OF_CELL = { offset: 3, size: 2 }
export const CELL_CONTENT_AREA = { offset: 5, size: 2 }
export const FRAGMENTED_FREE_BYTE = { offset: 7, size: 1 }
export const RIGHT_MOST_POINTER = { offset: 8, size: 4 }
export const CELL_PTR_LENGTH = 2
export const INDEX_INTERIOR_PAGE = 2;
export const INDEX_LEAF_PAGE = 10;
export const TABLE_INTERIOR_PAGE = 5;
export const TABLE_LEAF_PAGE = 13;
